### ISSUE TITLE
bib2df parsing issues

### ISSUE THREAD

**Issue by mattwarkentin** [nucleic-acid/namedropR#49]
Hi @nucleic-acid,

Cool package! 

I was running into a frustrating issue when I tried to play around with it, but it turns out it is caused by `bib2df`. A related issue is found here: https://github.com/ropensci/bib2df/issues/53

Unfortunately, Google Scholar provides BibTeX citations without whitespace around the equals sign, by default. So any citation grabbed from Google Scholar fails when parsed by `bib2df` and thus creates incomplete visual citations via `drop_name()`.

Just something you might want to know/guard against in this package until it is resolved in that package.

**Comment by nucleic-acid** [comment]
Thanks @mattwarkentin for the feedback!
Since I never pulled references from Google Scholar, I wasn't aware of this issue. Thanks for pointing it out.

I used bib2df, as bibtex was orphaned on CRAN and back then it was not clear whether it would ever return. I'll have to think on  how to catch this problem. If you have suggestions, please do share them!

**Comment by nucleic-acid** [comment]
Seeing the active development on the bibtex package (https://github.com/ropensci/bibtex/issues/45), i might switch back to that on the long run.

**Comment by mattwarkentin** [comment]
Thanks for the quick reply.

Yes, perhaps `bibtex` would be a good long-term solution if it is actively being maintained now. So long as it meets the same needs as `bib2df`.
